name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp@3.0.6-alpha

      - name: Check clasp version
        run: clasp --version

      - name: Authenticate clasp with service account
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS_B64 }}" | base64 -d > creds.json
          clasp login --service-account --creds creds.json

      - name: Push to Google Apps Script
        run: clasp push
