name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp@2.5.0

      - name: Authenticate clasp
        env:
          GCP_CLASP_TOKEN: ${{ secrets.GCP_CLASP_TOKEN }}
        run: |
          echo "$GCP_CLASP_TOKEN" > ~/.clasprc.json

      - name: Toon directory inhoud
        run: ls -l

      - name: Clasp status
        run: clasp status

      - name: Check content Code.js
        run: cat Code.js

      - name: Deploy with clasp
        run: clasp push